# Generated by Django 6.0.1 on 2026-01-21 22:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pokedex_id', models.IntegerField()),
                ('level', models.IntegerField(default=1)),
                ('type_primary', models.CharField(default='Normal', max_length=50)),
                ('type_secondary', models.CharField(blank=True, max_length=50, null=True)),
                ('capture_id', models.CharField(help_text='Unique ID from the capture device', max_length=50, unique=True)),
                ('is_shiny', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
