# Generated by Django 6.0.1 on 2026-02-02 13:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matricola',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricola', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'matricole',
            },
        ),
    ]